name: freshkeep
description: "A FreshPick project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  crypto: ^3.0.3
  path_provider: ^2.1.2
  fl_chart: ^0.65.0 # Thêm thư viện biểu đồ
  cloud_functions: ^4.6.5
  firebase_core: ^2.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env