name: freshkeep
description: "A FreshPick project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  crypto: ^3.0.3
  path_provider: ^2.1.2
  fl_chart: ^0.65.0
  cloud_functions: ^5.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/